OUT_FOLDER: "results_study_case_2"
SAMPLE_KEY: "example/aj_trio/study_case_2/sampleKey.txt"

TOOLS:
  - "manta"
  - "smoove"
  - "delly"

# Reference genome files
REFERENCE_FASTA: "data/ref/human_g1k_v37.fasta"
REF_BUILD: "37"

# Gencode GTF for SV annotation
GENCODE_GTF: "data/annotation/gtf/gencode.v38lift37.annotation.nochr.gtf.gz"

# Custom SVs for genotyping (optional)
SV_PANEL:
  - "data/sv_panel/hg002/variants.22XY.vcf"

# Custom annotations (optional)
ANNOTATION_BED: 
  - "data/annotation/custom/astrocytes_H3K27ac.bed"
  - "data/annotation/custom/microglia_H3K27ac.bed"
  - "data/annotation/custom/neurons_H3K27ac.bed"
  - "data/annotation/custom/oligodendrocytes_H3K27ac.bed"
