# All paths set on this file are relative to the workdir (if not absolute). 
workdir: "/hpc/users/viallr01/ad-omics/ricardo/MyRepo/snakeSV/"

OUT_FOLDER: "results_GIAB_HGSVC2"
SAMPLE_KEY: "config/sampleKey.txt"

TOOLS: 
  - "manta"
  - "smoove" 
  - "delly"

# Custom SVs for genotyping (optional)
SV_PANEL:
  - "data/sv_panel/HGSVC2/merged.survivor.h37.vcf"

# Reference genome files
REFERENCE_FASTA: "data/ref/human_g1k_v37.fasta"
REF_BUILD: "37"

# Gencode GTF for SV annotation
#GENCODE_GTF: "data/annotation/gtf/gencode.v38lift37.annotation.nochr.gtf.gz"

# Custom annotations (optional)
#ANNOTATION_BED: 
#  - "data/annotation/custom/astrocytes_H3K27ac.bed"
#  - "data/annotation/custom/microglia_H3K27ac.bed"
#  - "data/annotation/custom/neurons_H3K27ac.bed"
#  - "data/annotation/custom/oligodendrocytes_H3K27ac.bed"

# Custom tmp folder (if not /tmp)
TMP_DIR: "~/ad-omics/ricardo/tmp/"

BENCHMARK: True
# If BENCHMARK=True set up the VCF and BED files to compare using truvari
GIAB_VCF: "data/bench/HG002_SVs_Tier1_v0.6.vcf.gz"
GIAB_BED: "data/bench/HG002_SVs_Tier1_v0.6.bed"
