# All paths set on this file are relative to the workdir (if not absolute).
SAMPLE_KEY: "sampleKey.txt"

TOOLS: 
  - "manta"
  - "delly"
  - "smoove"
  - "dysgu"

STR_TOOLS:
  - "strling"

# Reference genome files
REFERENCE_FASTA: "ref.fasta"
REF_BUILD: "37"
