# All paths set on this file are relative to the workdir (if not absolute).
SAMPLE_KEY: "sampleKey.txt"

TOOLS: 
  - "manta"
  - "delly"

# Reference genome files
REFERENCE_FASTA: "ref.fasta"
REF_BUILD: "37"

# Gencode GTF for SV annotation
GENCODE_GTF: "gencode.gtf.gz"

